package inspect

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strings"

	"github.com/UnitVectorY-Labs/oci-supplychain-observatory/internal/oci"
)

const maxRenderedComponents = 200

func analyzeArtifact(artifact *Artifact) {
	doc, ok := decodeArtifactDocument(artifact.Raw)
	if !ok {
		artifact.Purpose = artifact.Type
		return
	}

	predicateType := stringAt(doc, "predicateType")
	predicate, _ := doc["predicate"].(map[string]any)
	content := doc
	if predicate != nil {
		content = predicate
	}

	switch {
	case isSPDX(content, predicateType):
		artifact.Purpose = "SPDX SBOM"
		artifact.Type = "SBOM attestation"
		artifact.Facts, artifact.Components, artifact.ComponentsTruncated = analyzeSPDX(content, doc)
	case isCycloneDX(content, predicateType):
		artifact.Purpose = "CycloneDX SBOM"
		artifact.Type = "SBOM attestation"
		artifact.Facts, artifact.Components, artifact.ComponentsTruncated = analyzeCycloneDX(content, doc)
	case strings.Contains(strings.ToLower(predicateType), "slsa") || content["buildDefinition"] != nil || content["builder"] != nil:
		artifact.Purpose = "SLSA build provenance"
		artifact.Type = "Attestation"
		artifact.Facts = analyzeProvenance(doc, content)
	case doc["critical"] != nil:
		artifact.Purpose = "Container image signature"
		artifact.Facts = analyzeSignature(doc)
	default:
		artifact.Purpose = artifact.Type
		if predicateType != "" {
			artifact.Facts = append(artifact.Facts, oci.KV{Key: "Predicate", Value: predicateType})
		}
	}
}

func decodeArtifactDocument(raw []byte) (map[string]any, bool) {
	var doc map[string]any
	if json.Unmarshal(raw, &doc) != nil {
		return nil, false
	}
	for _, path := range [][]string{{"dsseEnvelope", "payload"}, {"payload"}, {"Payload"}} {
		if payload := nestedString(doc, path...); payload != "" {
			if decoded, ok := decodeBase64(payload); ok {
				var nested map[string]any
				if json.Unmarshal(decoded, &nested) == nil {
					return nested, true
				}
			}
		}
	}
	return doc, true
}

func decodeBase64(value string) ([]byte, bool) {
	for _, encoding := range []*base64.Encoding{base64.StdEncoding, base64.RawStdEncoding, base64.URLEncoding, base64.RawURLEncoding} {
		decoded, err := encoding.DecodeString(strings.TrimSpace(value))
		if err == nil && json.Valid(decoded) {
			return decoded, true
		}
	}
	return nil, false
}

func isSPDX(doc map[string]any, predicateType string) bool {
	return stringAt(doc, "spdxVersion") != "" || strings.Contains(strings.ToLower(predicateType), "spdx")
}

func isCycloneDX(doc map[string]any, predicateType string) bool {
	return strings.EqualFold(stringAt(doc, "bomFormat"), "CycloneDX") || strings.Contains(strings.ToLower(predicateType), "cyclonedx")
}

func analyzeSPDX(doc, statement map[string]any) ([]oci.KV, []Component, bool) {
	facts := []oci.KV{{Key: "Format", Value: valueOr(stringAt(doc, "spdxVersion"), "SPDX")}}
	appendFact(&facts, "Document", stringAt(doc, "name"))
	appendSubjects(&facts, statement)
	if creation, ok := doc["creationInfo"].(map[string]any); ok {
		appendFact(&facts, "Created", stringAt(creation, "created"))
		if creators := stringSlice(creation["creators"]); len(creators) > 0 {
			appendFact(&facts, "Generated by", strings.Join(creators, ", "))
		}
	}
	packages, _ := doc["packages"].([]any)
	relationships, _ := doc["relationships"].([]any)
	facts = append(facts,
		oci.KV{Key: "Components", Value: fmt.Sprint(len(packages))},
		oci.KV{Key: "Relationships", Value: fmt.Sprint(len(relationships))},
	)

	components := make([]Component, 0, min(len(packages), maxRenderedComponents))
	for _, item := range packages {
		pkg, ok := item.(map[string]any)
		if !ok {
			continue
		}
		component := Component{
			Name:     stringAt(pkg, "name"),
			Version:  stringAt(pkg, "versionInfo"),
			Supplier: stringAt(pkg, "supplier"),
			License:  valueOr(stringAt(pkg, "licenseConcluded"), stringAt(pkg, "licenseDeclared")),
		}
		if refs, ok := pkg["externalRefs"].([]any); ok {
			for _, refAny := range refs {
				ref, _ := refAny.(map[string]any)
				if strings.EqualFold(stringAt(ref, "referenceType"), "purl") {
					component.PURL = stringAt(ref, "referenceLocator")
					component.Ecosystem, component.Platform = purlDetails(component.PURL)
					break
				}
			}
		}
		if len(components) < maxRenderedComponents {
			components = append(components, component)
		}
	}
	return facts, components, len(packages) > maxRenderedComponents
}

func analyzeCycloneDX(doc, statement map[string]any) ([]oci.KV, []Component, bool) {
	facts := []oci.KV{{Key: "Format", Value: "CycloneDX " + stringAt(doc, "specVersion")}}
	appendSubjects(&facts, statement)
	componentsRaw, _ := doc["components"].([]any)
	dependencies, _ := doc["dependencies"].([]any)
	facts = append(facts,
		oci.KV{Key: "Components", Value: fmt.Sprint(len(componentsRaw))},
		oci.KV{Key: "Dependencies", Value: fmt.Sprint(len(dependencies))},
	)
	if metadata, ok := doc["metadata"].(map[string]any); ok {
		appendFact(&facts, "Created", stringAt(metadata, "timestamp"))
	}
	components := make([]Component, 0, min(len(componentsRaw), maxRenderedComponents))
	for _, item := range componentsRaw {
		entry, ok := item.(map[string]any)
		if !ok {
			continue
		}
		component := Component{
			Name:     stringAt(entry, "name"),
			Version:  stringAt(entry, "version"),
			Supplier: nestedString(entry, "supplier", "name"),
			PURL:     stringAt(entry, "purl"),
		}
		component.Ecosystem, component.Platform = purlDetails(component.PURL)
		if len(components) < maxRenderedComponents {
			components = append(components, component)
		}
	}
	return facts, components, len(componentsRaw) > maxRenderedComponents
}

func analyzeProvenance(statement, predicate map[string]any) []oci.KV {
	var facts []oci.KV
	appendSubjects(&facts, statement)
	appendFact(&facts, "Predicate", stringAt(statement, "predicateType"))

	buildDefinition, _ := predicate["buildDefinition"].(map[string]any)
	if buildDefinition != nil {
		appendFact(&facts, "Build type", stringAt(buildDefinition, "buildType"))
		external, _ := buildDefinition["externalParameters"].(map[string]any)
		appendFact(&facts, "Source", nestedString(external, "workflow", "repository"))
		appendFact(&facts, "Source ref", nestedString(external, "workflow", "ref"))
		appendFact(&facts, "Workflow", nestedString(external, "workflow", "path"))
		appendFact(&facts, "Dockerfile", nestedString(external, "configSource", "path"))
		if rootArgs, ok := nestedMap(external, "request", "root", "request", "args"); ok {
			appendFact(&facts, "Source", stringAt(rootArgs, "vcs:source"))
			appendFact(&facts, "Commit", stringAt(rootArgs, "vcs:revision"))
		}
		if deps, ok := buildDefinition["resolvedDependencies"].([]any); ok {
			facts = append(facts, oci.KV{Key: "Resolved inputs", Value: fmt.Sprint(len(deps))})
			for _, depAny := range deps {
				dep, _ := depAny.(map[string]any)
				if strings.HasPrefix(stringAt(dep, "uri"), "git+") {
					appendFact(&facts, "Source material", stringAt(dep, "uri"))
					if digest, ok := dep["digest"].(map[string]any); ok {
						appendFact(&facts, "Commit", firstMapValue(digest))
					}
				}
			}
		}
	}
	if builder, ok := nestedMap(predicate, "runDetails", "builder"); ok {
		appendFact(&facts, "Builder", stringAt(builder, "id"))
	}
	if metadata, ok := nestedMap(predicate, "runDetails", "metadata"); ok {
		appendFact(&facts, "Build run", stringAt(metadata, "invocationId"))
		appendFact(&facts, "Started", stringAt(metadata, "startedOn"))
		appendFact(&facts, "Finished", stringAt(metadata, "finishedOn"))
	}
	// SLSA v0.2 fields.
	if builder, ok := predicate["builder"].(map[string]any); ok {
		appendFact(&facts, "Builder", stringAt(builder, "id"))
	}
	appendFact(&facts, "Build type", stringAt(predicate, "buildType"))
	return uniqueFacts(facts)
}

func analyzeSignature(doc map[string]any) []oci.KV {
	var facts []oci.KV
	if critical, ok := doc["critical"].(map[string]any); ok {
		appendFact(&facts, "Signature type", stringAt(critical, "type"))
		appendFact(&facts, "Reference", nestedString(critical, "identity", "docker-reference"))
		appendFact(&facts, "Covers", nestedString(critical, "image", "docker-manifest-digest"))
	}
	if optional, ok := doc["optional"].(map[string]any); ok {
		appendFact(&facts, "Signer", stringAt(optional, "Subject"))
		appendFact(&facts, "Issuer", stringAt(optional, "Issuer"))
	}
	return facts
}

func appendSubjects(facts *[]oci.KV, statement map[string]any) {
	subjects, _ := statement["subject"].([]any)
	for _, subjectAny := range subjects {
		subject, _ := subjectAny.(map[string]any)
		name := stringAt(subject, "name")
		digest, _ := subject["digest"].(map[string]any)
		value := strings.TrimSpace(name + " " + firstMapValue(digest))
		appendFact(facts, "Covers", value)
	}
}

func appendFact(facts *[]oci.KV, key, value string) {
	if strings.TrimSpace(value) != "" {
		*facts = append(*facts, oci.KV{Key: key, Value: value})
	}
}

func uniqueFacts(facts []oci.KV) []oci.KV {
	seen := map[string]bool{}
	out := make([]oci.KV, 0, len(facts))
	for _, fact := range facts {
		key := fact.Key + "\x00" + fact.Value
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, fact)
	}
	return out
}

func purlDetails(purl string) (string, string) {
	if !strings.HasPrefix(purl, "pkg:") {
		return "", ""
	}
	value := strings.TrimPrefix(purl, "pkg:")
	ecosystem, rest, _ := strings.Cut(value, "/")
	parsed, _ := url.Parse("https://purl.invalid/" + rest)
	platform := parsed.Query().Get("arch")
	if osName := parsed.Query().Get("os"); osName != "" {
		platform = strings.Trim(strings.Join([]string{osName, platform}, "/"), "/")
	}
	return ecosystem, platform
}

func nestedString(doc map[string]any, path ...string) string {
	current := any(doc)
	for _, key := range path {
		object, ok := current.(map[string]any)
		if !ok {
			return ""
		}
		current = object[key]
	}
	value, _ := current.(string)
	return value
}

func nestedMap(doc map[string]any, path ...string) (map[string]any, bool) {
	current := any(doc)
	for _, key := range path {
		object, ok := current.(map[string]any)
		if !ok {
			return nil, false
		}
		current = object[key]
	}
	value, ok := current.(map[string]any)
	return value, ok
}

func stringAt(doc map[string]any, key string) string {
	value, _ := doc[key].(string)
	return value
}

func stringSlice(value any) []string {
	items, _ := value.([]any)
	result := make([]string, 0, len(items))
	for _, item := range items {
		if text, ok := item.(string); ok {
			result = append(result, text)
		}
	}
	return result
}

func firstMapValue(values map[string]any) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		if value, ok := values[key].(string); ok && value != "" {
			return key + ":" + value
		}
	}
	return ""
}

func valueOr(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}
